### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by discordianfish**
Hi,

this Dockerfile builds a peerflix-server Docker image. I've added my fork to my hub account: https://hub.docker.com/u/fish/peerflix-server

If you're up for it, I'd suggest you sign up as well so you can provide official images.
Using this image is as simple as running:

    docker run -p 9000:9000 fish/peerflix-server

You can always build the image locally by running `docker build -t peerflix-server .` in this repo.

### CODE REVIEW

**Comment by asapach** [comment]
I think it would be more efficient to install the package from NPM rather than building it from source. Also, I would probably add [forever](https://www.npmjs.com/package/forever) support and maybe an [upstart script](https://github.com/asapach/peerflix-server/issues/10#issuecomment-61409423) if it makes sense for docker.

**Comment by discordianfish** [comment]
@asapach The nice thing about building from souce is that the docker image automatically gets updated when someone pushes change to peerflix-server.
Using upstart in general is discouraged since a container should ideally just run one application and forever isn't really necessary, since docker can take care of restarting failed containers (see docker run --restart).

**Comment by asapach** [comment]
Next question: you probably would want to move the torrent storage(`/tmp/torrent-stream`) outside of the container into a separate volume.

**Comment by asapach** [comment]
> Next question: you probably would want to move the torrent storage(/tmp/torrent-stream) outside of the container into a separate volume.

And maybe also the config folder:`~/.config/peerflix-server/`

**Comment by discordianfish** [comment]
@asapach I would keep ~/.config/peerflix-server in the container. If people need to customize the config, they can either create their custom docker image based off this image like this (with my fork as example)

    FROM fish/peerflix-server
    ADD config/ /home/app/.config/peerflix-server

Or they can bind-mount a directory from host with a config like this:

    docker run -v path/to/config:/home/app/.config/peerflix-server ...

**Comment by asapach** [comment]
Thanks, merged. I'll need to play with this.

**Comment by asapach** [comment]
Created the Docker repo: https://registry.hub.docker.com/u/asapach/peerflix-server/

**Pull request merged**
