### PR TITLE
Added push.js notification library

### PR DESCRIPTION
**Pull request by joshterrill**
Something that I added to my local instance of `peerflix-server` is [push.js](https://github.com/Nickersoft/push.js). It's a push notification library for the browser. I find it helpful so that as I'm downloading torrents and browsing other pages, it notifies me when my torrents are done. Unfortunately, the library has a bug where svg images aren't displayed in the icon area, so I created a png of the logo and am using that.

### CODE REVIEW

**Comment by asapach** [comment]
This looks great, but there's one issue: `uninterested` event is not a good indicator of a torrent being finished. It fires in several other cases:
* When you uncheck a checkbox (deselect a file)
* When a single selected file is complete

I'll see if I can add a new event specifically for this.

**Comment by asapach** [comment]
Done. Please try it out before I publish it to npm.

**Comment by joshterrill** [comment]
Looks great to me. Works perfectly!

**Comment by asapach** [comment]
Thanks. Published :+1:

**Comment by joshterrill** [comment]
No problem! I opened an issue with the push.js repo saying SVG's don't work with the library, but apparently [this is an issue with chromium's notification library](https://bugs.chromium.org/p/chromium/issues/detail?id=478654). So looks like until that is resolved, we'll have to use a PNG.

**Pull request merged**
